kind: Plan
apiVersion: api.webmethods.io/beta
metadata:
  name: Basic Plan
  namespace: Gestione Ordini
  version: '1.0'
  tags: []
  description: ''
spec:
  qos:
    withQuota: []
    withRateLimit: []
  pricing:
    value: 10
    currency: ''
  isApprovalRequired: false
